### ISSUE TITLE
"Intent of application of Aniket Giri"

### ISSUE THREAD

**Issue by AniketDGiri** [pgRouting/GSoC-pgRouting#136]
- [x] Intent of application
- [ ] Experience with GitHub & Git
- [ ] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

**Comment by AniketDGiri** [comment]
Task 1: (Intent Of the application:)
Dear Community Members,
I am Aniket Giri from India. Currently, I am pursuing Masters in Geoinformatics from CSRE, Indian Institute of Technology Bombay (IITB). I have my bachelor's in Computer Science. I have had exposure to GIS, spatial databases in the last semester. I have implemented many algorithms during my BTech and MTech course as well. I also have built a web-based application for Augmented Reality based GIS application using AR.js
Below is the link to my GitHub repo for the above project:
https://github.com/AniketDGiri/GIS_Version_1
I am fond of the open-source community as it provides me an opportunity to keep my skills updated, build connections, and improve communications skills. Thus, I would love to contribute to Google Summer of Code 2021. I have gone through the documentation. I would be very grateful to get any directions to pursue and participate in Google Summer of Code 2021 with your organization.

**Comment by cvvergara** [comment]
@AniketDGiri change the title of the issue to:
"Intent of application of Aniket Giri"

**Comment by cvvergara** [comment]
btw, I will put the checkmark on the comment when I consider a task if finished appropriately

**Comment by AniketDGiri** [comment]
@Vicky Vergara <vicky@georepublic.de>, Ok I will change the title as
mentioned above.

Thanks,
Aniket Giri

**Comment by AniketDGiri** [comment]
@cvvergara, I have changed the title as mentioned above.
Should I uncheck the tasks which I have already checked?

please let me know in case of any concerns.

Regards,
Aniket D Giri

**Comment by cvvergara** [comment]
The checkboxes here are for my use.
I dont see links for us to follow. From our point of view you haven't finished, you havent even started, as you haven't posted the links if any, of the issue tasks you created on your fork.

**Comment by cvvergara** [comment]
Did not apply for pgRouting
