### ISSUE TITLE
Intent of Application of Riya Singh

### ISSUE THREAD

**Issue by riyasingh1004** [pgRouting/GSoC-pgRouting#137]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by riyasingh1004** [comment]
Hi, I am Riya Singh, a 3rd year computer science undergraduate in Dayanand Sagar College in Bengaluru. I love contributing to open source and learning new algorithms. I have a good grasp on C++ and data structures and algorithms. pgRouting aligned perfectly with my skillset and interests and I would be very grateful to contribute to this project as a part of GSoc 2021.

**Comment by riyasingh1004** [comment]
[**Task 2**](https://github.com/riyasingh1004/GSoC-pgRouting/issues/1)
[**PR for Task 2**](https://github.com/pgRouting/GSoC-pgRouting/pull/144)

**Comment by cvvergara** [comment]
I will check the checkboxes in this issue, it is the mark for me track what I have seen

**Comment by riyasingh1004** [comment]
@cvvergara I have unchecked the boxes and will ask for review when done with the tasks.

**Comment by riyasingh1004** [comment]
@cvvergara  Please review.

**Comment by cvvergara** [comment]
Please leave a link here to your proposal

**Comment by cvvergara** [comment]
Did not apply to pgRouting
