### ISSUE TITLE
Intent of Application of Veenit Kumar

### ISSUE THREAD

**Issue by veenits123** [pgRouting/GSoC-pgRouting#138]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by Veenits123** [comment]
Hi there,
My name is Veenit Kumar, I am a Computer Science undergrad currently in 3rd year from Netaji Subhash Engineering College, Kolkata, India. 

I have decent experience working with C++, data structures and  Algorithms, Git and Github and implementing various algorithms.
I love to work in a challenging environment to enhance my Skills, Experience and Knowledge and I believe GSoC is the best place for this.
I am looking forward to contributing to pgRouting.

Thank You!!

**Comment by Veenits123** [comment]
##  Experience with GitHub & Git

**Link for the task:**
https://github.com/Veenits123/GSoC-pgRouting/issues/1

**Link for the PR:**
https://github.com/pgRouting/GSoC-pgRouting/pull/142

**Comment by Veenits123** [comment]
##  Build locally pgRouting

**Comment by Veenits123** [comment]
##  Get familiar with C++

**Comment by Veenits123** [comment]
##  Get familiar with pgRouting

**Comment by Veenits123** [comment]
@cvvergara Please review!!

**Comment by cvvergara** [comment]
Please leave a link here to your proposal

**Comment by Veenits123** [comment]
Here is the link to my proposal: 
```
https://docs.google.com/document/d/12aHFXTob70r5lljas7w7Bfht_Z4kE4VQewrA6poOsVs/edit?usp=sharing
```
I am still working on the **"14. Detailed Proposal"** part.

**Comment by cvvergara** [comment]
Left you a lot of comments

**Comment by Veenits123** [comment]
Hi @cvvergara, I have improved the suggestion provided by you and finalised the proposal from my side, can you please take a look. Thanks!
I have also shared my draft proposal on the GSoC website and sent for feedback from the community to the following mailing list:
- https://lists.osgeo.org/pipermail/soc/2021-March/004660.html
- https://lists.osgeo.org/pipermail/discuss/2021-March/039291.html
- https://lists.osgeo.org/pipermail/pgrouting-dev/2021-March/002187.html
