### ISSUE TITLE
Intent of Application of Ashish Kumar

### ISSUE THREAD

**Issue by krashish8** [pgRouting/GSoC-pgRouting#140]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by krashish8** [comment]
Hi, I am Ashish Kumar, a third-year undergraduate student from IIT (BHU) Varanasi, India pursuing Computer Science and Engineering. I have been contributing to pgRouting since last year, so I am pretty familiar with the codebase of pgRouting. I also have a good experience in C++, Git/GitHub, and graph algorithms.

I contributed to pgRouting in GSoC '20 and added some functionality to it, particularly the Boost Graph algorithms. I would like to take another opportunity to contribute to pgRouting during the GSoC '21 period. Ideas 3 and 4 interest me, and the VROOM and similar optimizations related to VRP functions are of particular interest to the community as well. Therefore, I'm looking forward to contributing to pgRouting, to add the VRP functionality with VROOM on the database.

**Comment by krashish8** [comment]
- [Link for Task 2](https://github.com/krashish8/GSoC-pgRouting/issues/8)
  - [Link for the PR](https://github.com/pgRouting/GSoC-pgRouting/pull/141)
- [Link for Task 3](https://github.com/krashish8/GSoC-pgRouting/issues/9)
- [Link for Task 4](https://github.com/krashish8/GSoC-pgRouting/issues/10)
- [Link for Task 5](https://github.com/krashish8/GSoC-pgRouting/issues/11)

**Comment by krashish8** [comment]
@cvvergara Please review!

**Comment by cvvergara** [comment]
Please leave a link here to your proposal

**Comment by krashish8** [comment]
**Link to the Proposal**: [VRP functionality with VROOM on the database for pgRouting](https://docs.google.com/document/d/1f5wTZChYSMI3XfQr0D-WKpEAVNylh8JG4vHm7mNOEzU/edit?usp=sharing) (Idea 3)

**Comment by cvvergara** [comment]
You just are missing to fill the time line.
You would need to use your imagination for that.

**Comment by krashish8** [comment]
I've made the tentative schedule of the tasks, based on my imagination. Please take a look!
