### ISSUE TITLE
Intent of Application of Saurav Uppoor

### ISSUE THREAD

**Issue by sauravUppoor** [pgRouting/GSoC-pgRouting#145]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by sauravUppoor** [comment]
Hello,
I am Saurav Uppoor, currently a 3rd year Computer Engineering undergraduate from TSEC, University of Mumbai, India. I have decent knowledge in C/C++, Data Structures Algorithms, Graph Theory and Version Control. I have gone through the Idea List and found Ideas 2 and 6 intriguing. Having some experience in open source previously, I would like to contribute to pgRouting.

**Comment by sauravUppoor** [comment]
- [Link for Task 2](https://github.com/sauravUppoor/GSoC-pgRouting/issues/1)
  - [Link for PR](https://github.com/pgRouting/GSoC-pgRouting/pull/146)

**Comment by sauravUppoor** [comment]
- [Link for Task 3](https://github.com/sauravUppoor/GSoC-pgRouting/issues/2)

**Comment by sauravUppoor** [comment]
- [Link for Task 4](https://github.com/sauravUppoor/GSoC-pgRouting/issues/3)

**Comment by sauravUppoor** [comment]
- [Link for Task 5](https://github.com/sauravUppoor/GSoC-pgRouting/issues/4)

**Comment by sauravUppoor** [comment]
**Proposal Link**: https://docs.google.com/document/d/1og12ZNgPk6B_3XGXex7HFiCS6ktMKE_trfIuzR5Gedc/edit?usp=sharing

**Comment by cvvergara** [comment]
@sauravUppoor Left you some comments

**Comment by sauravUppoor** [comment]
@cvvergara I have made the changes you had suggested and also made some final additions to the proposal. Could you please go through it and give some suggestions.
