### ISSUE TITLE
Intent of Application of Kishan Kumar

### ISSUE THREAD

**Issue by kineticdud** [pgRouting/GSoC-pgRouting#147]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by kineticdud** [comment]
[Task 2](https://github.com/kineticdud/GSoC-pgRouting/issues/1)

**Comment by kineticdud** [comment]
[Task 3](https://github.com/kineticdud/GSoC-pgRouting/issues/2)

**Comment by cvvergara** [comment]
I will be the one putting a check on the tasks I have seen. (that is why I unchecked the boxes)
Put a paragraph or two on a comment on this issue talking about yourself

**Comment by kineticdud** [comment]
I am Kishan Kumar, a final year undergrad student at IIT Roorkee having major in Computer Science. I am fluent in C/C++, python. I am new to open source but have done projects related to app development, operating systems, image processing.

**Comment by kineticdud** [comment]
[Task 4](https://github.com/kineticdud/GSoC-pgRouting/issues/3)

**Comment by kineticdud** [comment]
[Task 5](https://github.com/kineticdud/GSoC-pgRouting/issues/4)

**Comment by kineticdud** [comment]
Hello Ma'am, I am interested in implementing the Tour Recommendation algorithm. I have gone through a couple of research papers and found different methods of implementing this depending on various use cases. Can you please tell me more about
algorithm Georepublic has used?

**Comment by kineticdud** [comment]
@cvvergara Please review.

**Comment by dkastl** [comment]
@kineticdud , have you already written down some notes about your research/own idea?

**Comment by kineticdud** [comment]
Please see this I have collected few points from research.
https://docs.google.com/document/d/1dDAj-4LHZYoyxjUukOxM0Rvgpk1OGOLHDCeINf3bMLY/edit

**Comment by cvvergara** [comment]
Please start writing your proposal.

**Comment by cvvergara** [comment]
Dont forget to put the proposal link in the issue

**Comment by kineticdud** [comment]
@cvvergara Can I implement Hawick Circuit using boost library for idea 2?

**Comment by kineticdud** [comment]
https://docs.google.com/document/d/1reFDJcFe8no9OJACCH0wt2YmR0crvfD7u13k-ctrUa8/edit#
@cvvergara Please review. This proposal is for idea 2. I have to complete [TODO] sections and modify other sections a little.
Waiting for your suggestions.

**Comment by cvvergara** [comment]
@kineticdud 
Left you some comments on your proposal
