### ISSUE TITLE
Intent of Application of Abhik Chakraborty

### ISSUE THREAD

**Issue by Abhik1998** [pgRouting/GSoC-pgRouting#150]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by Abhik1998** [comment]
****Task 2** Link:**

- [PR](https://github.com/pgRouting/GSoC-pgRouting/pull/151)
- [Issue in Fork](https://github.com/Abhik1998/GSoC-pgRouting/issues)

**Comment by Abhik1998** [comment]
@cvvergara: Tasks completed - Please review

**Comment by cvvergara** [comment]
Please write in a comment on this issue, a paragraph or two about yourself.
I un-checked  things that I need to see again, please don't check it back.

**Comment by cvvergara** [comment]
Please do not send private messages to my aaccound, use gitter to communicate with me

**Comment by Abhik1998** [comment]
> Please write in a comment on this issue, a paragraph or two about yourself.
> I un-checked things that I need to see again, please don't check it back.

Okay Cool!!

I am currently in the final year of BTech in the field of Computer Science at IIT Roorkee. I have been a part of many open sources programs like LFX (under Linux Foundation), Google Code-In, and WoC. I have developed many web applications and have sound knowledge of C(+ C++ + Java).

**Comment by cvvergara** [comment]
Please leave a link here to your proposal

**Comment by Abhik1998** [comment]
**Link to Proposal:**   [**Adding functionality to pgRoutingLayer**](https://iitracin-my.sharepoint.com/:p:/g/personal/achakraborty_cs_iitr_ac_in/EXPkm22XA1NNrzDvv36snIkB692zsqzHTwyGdMFEvDu3SQ?e=nQnnil)

**Comment by cvvergara** [comment]
@Abhik1998 can you write your proposal on a shared document so we can add comments on the side.
Proposal should be in a document  document not on a presentation.

**Comment by cvvergara** [comment]
We already have
pgr_bridges, pgr_articulationPoints and pgr_connectedComponents
https://docs.pgrouting.org/3.2/en/components-family.html
Please make sure you verify what you choose is not already implemented

**Comment by cvvergara** [comment]
I see, its for pgRoutingLayers
When you write your proposal, make it clear that is for the pgRoutingLayers Idea.
Never mind last comment

**Comment by Abhik1998** [comment]
> @Abhik1998 can you write your proposal on a shared document so we can add comments on the side.
> Proposal should be in a document not on a presentation.

Okay @cvvergara , then I am writing it up on a doc.

**Comment by Abhik1998** [comment]
@cvvergara I have added up some info about the pgRoutingLayer and have made some changes to the proposal.
