### ISSUE TITLE
Intent of Application of Rishi Sethia

### ISSUE THREAD

**Issue by rishisethia258** [pgRouting/GSoC-pgRouting#152]
- [x] Intent of application 
- [ ] Experience with GitHub & Git
- [ ] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

**Comment by rishisethia258** [comment]
Hi, I am Rishi Sethia. I am a Sophomore at Indian Institute of Technology Roorkee, pursuing majors in Mechanical Engineering. I am having decent knowledge of C++, Data Structures and Algorithms , Databases and Version control. I love contributing to open source, as it is always a great learning experience. Apart from contributing to open source, I also do competitive programming and I go by the handle 'rs258' on codeforces. I found projects in pgRouting to be very exciting and also match my skillsets. I am looking forward to contribute to pgRouting.

**Comment by cvvergara** [comment]
The check boxes in this issue are for me to use.
If you see a box checked is because I saw that task

**Comment by AnandIISc** [comment]
Hi, I am Anand Kumar. I am a Master's student at the Indian Institute of Science Bangalore, have done Bachelors's in Information. 
Technology. I am having a good knowledge of C++, Data Structures and Algorithms, DBMS. I love contributing to open source, as it is always a great learning experience. Besides contributing to open source, I found projects in pgRouting to be very exciting and match my skillsets. I would like to contribute to pgRouting.

**Comment by cvvergara** [comment]
Did not apply for pgRouting
