### ISSUE TITLE
Intent of Application of  Ayush Paliwal

### ISSUE THREAD

**Issue by ayushvpaliwal** [pgRouting/GSoC-pgRouting#154]
- [x] intent of application
- [x] Experiance with Github & Git
- [x] Build locally pgRouting
- [x] Get fimiliar with C++
- [x] Get fimiliar with pgRouting

**Comment by ayushvpaliwal** [comment]
- [ ] intent of application
- [ ] Experiance with Github & Git
- [ ] Build locally pgRouting
- [ ] Get fimiliar with C++
- [ ] Get fimiliar with pgRouting

**Comment by cvvergara** [comment]
Please edit your comments
on the first one put the checkboxes, on the second one is where you talk about your self.

**Comment by ayushvpaliwal** [comment]
[Link of Task 2](https://github.com/ayushvpaliwal/GSoC-pgRouting/issues/1)
[Link of Task 3](https://github.com/ayushvpaliwal/GSoC-pgRouting/issues/2)
[Link of Task 4](https://github.com/ayushvpaliwal/GSoC-pgRouting/issues/3)
[Link of Task 5](https://github.com/ayushvpaliwal/GSoC-pgRouting/issues/4)

**Comment by ayushvpaliwal** [comment]
@cvvergara please review!

**Comment by ayushvpaliwal** [comment]
I have gone through some research paper and took some key points that will help this project, and I have some of my ideas to implement. I want to discuss them with the mentor of this project. 
@dkastl @cvvergara  please review it
link of google doc : https://docs.google.com/document/d/1f2w6PgXFtbE2Wr55CWyHfZEbjHB9RHrbtp9J8VYMgJ0/edit?usp=sharing

**Comment by dkastl** [comment]
@ayushvpaliwal , I received the access notification and took a very brief look. Thanks for writing your idea down! 

What came to my mind first is, that your idea looks more like an application than an algorithm. But with pgRouting we just build the tools to develop applications, which should be as generic as possible. But maybe your proposal in the current state is more of an illustration?

To give you some hints, what I would expect from a "tour recommendation" function:
- take as input a list of node ID's that should be all visited with the tour, but at least one node.
- optionally return to the start node at the end of the tour
- take into account the "costs" of the network. You can see in other pgRouting functions how flexible costs can be. They can be time or distance or just anything user want.
- allow to specify an expected "length" (cost) of the route. It will probably not be possible get the exact cost of the route.

**Comment by ayushvpaliwal** [comment]
@dkastl thanks for your feedback. I get your point and so updated the draft. Please have look in it.
Link of google doc :  https://docs.google.com/document/d/1DALi-gRy2xu29VX5DTY5WCwVXOzUsGPs9uRzqzVMLFI/edit?usp=sharing

**Comment by cvvergara** [comment]
Please, I will use the lik above as your proposal link, please give it the form the proposal that is expected by GSoV, OSgeo & pgRouting.

**Comment by ayushvpaliwal** [comment]
doc link : https://docs.google.com/document/d/1pnVpct0tippq82ibHm-HECipOU5eIv75MDFeNhIvt_o/edit?usp=sharing
@cvvergara please review. This proposal is for idea 2.  I have left past programming experience and resume section blank. I will update it 2-3 days.

**Comment by ayushvpaliwal** [comment]
proposal doc link : https://docs.google.com/document/d/1XxzogyVvkyyDXoUrL94ZP6w7ffRLutuLiHUQHmp0mDw/edit?usp=sharing
@cvvergara please review!!

**Comment by ayushvpaliwal** [comment]
@cvvergara ma'am BOOST has not provided a cpp file for the algorithms. So I wrote a cpp file taking the same example graph which BOOST used in other algorithms.
Is this right, or you would suggest something on this?

**Comment by ayushvpaliwal** [comment]
@cvvergara please review my proposal above!! I have completed [TODO] part.
