### ISSUE TITLE
Intent of Application of Shobhit Chaurasia

### ISSUE THREAD

**Issue by shobhit162** [pgRouting/GSoC-pgRouting#159]
- [x]  Intent of application 
- [x]  Experience with GitHub & Git
- [x]  Build locally pgRouting
- [ ]  Get familiar with C++
- [x]  Get familiar with pgRouting

**Comment by shobhit162** [comment]
I'm Shobhit Chaurasia, a second year student from Hindustan College of Science and Technology, Mathura, India. I'm pursuing my B.tech from Computer Science branch. I have a decent knowledge of data structures and algorithm and also OOPs. I'm genuinely interested to contribute in pgRouting in idea no. 6 i.e. Tour recommendation algorithm. Looking forward to learn and grow with pgRouting.

**Comment by shobhit162** [comment]
[Link of PR](https://github.com/pgRouting/GSoC-pgRouting/pull/161)
[Link of Task 2](https://github.com/shobhit162/GSoC-pgRouting/issues/1)

**Comment by shobhit162** [comment]
[Link of Task 3](https://github.com/shobhit162/GSoC-pgRouting/issues/2)

**Comment by ashrafroni** [comment]
Please share your plan little bit more about the idea.. Also complete all the task please..

**Comment by shobhit162** [comment]
@ashrafroni As deadline is close, I would like to take some help from other participants. Ayush Palliwal initially opted for this idea but have prepared his proposal for idea no. 2. He has proposed a basic algorithm for this idea, so what modification or further improvement will you recommend to me?

**Comment by ashrafroni** [comment]
I am going through this and sharing you my thoughts

**Comment by ashrafroni** [comment]
Dear Shobhit,
I went through his proposal , his description is short and unclear what is
going to do. The graph image he sent seems good but algorithm explanation
is weak. Ayush may know the algorithm well , reading his documents I got
this sense. But why his algorithm takes such complexity , he did not
explain well.

I think we need a better explanation , if we have some time.

Regards
Ashraf

**Comment by ashrafroni** [comment]
Dear Sobhit,
Accidentally I went though
https://docs.google.com/document/d/1f2w6PgXFtbE2Wr55CWyHfZEbjHB9RHrbtp9J8VYMgJ0/edit?ts=60718665
This document only, in the thread I got more , I think I will comment going
into detail.
Sorry for the early comment.

Regards
Ashraf

**Comment by shobhit162** [comment]
Yes, I was talking about this document of Ayush and also I had discussed my idea yesterday on gitter channel. After you read that, let me know your thoughts and further enhancement. I will discuss my algorithm tomorrow, taking one user case so that it can be clear soon.

**Comment by ashrafroni** [comment]
Dear Shobhit,
I went through his official proposal in detail, a very well written
document.
I read the Cuthill–McKee algorithm as well and went through the boost graph
library.
I think we can go with him, If I get a chance to work with him , that will
be more interesting to me.
I want to work with 2 and 6 deeply.


Regards
Ashraf

**Comment by ashrafroni** [comment]
@shobhit162 Please follow his proposal and prepare yours also complete all the task please before submit.

**Comment by shobhit162** [comment]
@ashrafroni In his document he mentioned the time complexity of his algorithm which is O(n^5). Should I go ahead with the same?
Also, I'm confused between the two:-
a) User will input all points of interest (nodes) and then system will give a set of nodes that has to be visited within that list of POI.
b) User just input starting node and ending node and the system will automatically suggest the nodes within the available database.
Let me know which of the two sounds great.

**Comment by ashrafroni** [comment]
@shobhit162 I Accidentally wrote some comments, I removed them. Lets discuss the task no 6. What is your primary thought about solving this? can you please share? Then I can help you to go to next steps. Also Ayush is working on Idea 2, which is totally different. I am not going to discuss ayush issue in this thread anymore.

**Comment by ashrafroni** [comment]
@shobhit162  before that please complete all the task mentioned here and mark them done.

**Comment by shobhit162** [comment]
I will share my draft proposal on 12th April. We have 1 day for its improvement. Let me just finish my proposal and tasks.

**Comment by shobhit162** [comment]
@cvvergara and @ashrafroni please review my draft 
https://docs.google.com/document/d/1LPBY_V1Rfye2Z-4CqN8tDRB06YZ_w1b1EnL5m4x2uoU/edit?usp=sharing

**Comment by ashrafroni** [comment]
Thanks I am looking at it but time is short for final submission

**Comment by ashrafroni** [comment]
@shobhit162  please check the last 2 tasks in the 5 task list. About algorithm, If I were in the design sheet I would add an extra cost column which will be added in case of tour shortest path. The extra column add or subtract cost with the existing cost column. Why  should use prims algorithm ( expensive) ? The extra cost manipulation column will promote the shortest path touching all the tourist friendly edge as well as penalize the insecure path adding extra cost. I have more thoughts regarding this, which I will discuss step by step, in the GSoC time. As the time is short please check the task list and submit proposal.

**Comment by shobhit162** [comment]
About checking the task, it will be checked by mentors, students don't have to make the check itself and I will update the rest of the 2 tasks before the deadline. 
About your review on the proposal, I'm working on it, would also make a section of difference between "ksp" and my algorithm.

**Comment by shobhit162** [comment]
[Link of task 5](https://github.com/shobhit162/GSoC-pgRouting/issues/4)

**Comment by shobhit162** [comment]
[Link of Task 4](https://github.com/shobhit162/GSoC-pgRouting/issues/3)

**Comment by shobhit162** [comment]
@cvvergara check the 4th box, please!
