### ISSUE TITLE
Intent of Application of Hang Wu

### ISSUE THREAD

**Issue by nike0good** [pgRouting/GSoC-pgRouting#162]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [ ] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

**Comment by nike0good** [comment]
- [ ] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [ ] activate issues in your fork
- [ ] open an issue in your fork and put this content on the issue
- [ ] Clone your fork repository in your computer
- [ ] Create remote named `upstream` pointing to https://github.com/pgRouting/GSoC-pgRouting
- [ ] checkout to the `develop` branch of `upstream`
- [ ] create new branch with name `<your-git-nick>-test`
- [ ] Edit `doc/src/pgRouting-introduction.rst` and put your name on contributor
- [ ] push the newly created branch with the change 
- [ ] Create a pull request to https://github.com/pgRouting/GSoC-pgRouting
- [ ] put link of the PR and of the issue on a comment on the issue you created on [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository

**Comment by cvvergara** [comment]
Please add a paragraph about yourself in a comment

**Comment by nike0good** [comment]
Hello. My name is Hang Wu, a master student in Xi'an Jiaotong University. I have won many algorithm competitions during past few years. I think I can help pgRouting by working on the idea "GSoC 21: GRAPH C++ Boost Hawick circuits algorithms for pgRouting". I used to worked on GSOC-2019 for "GSoC 19: GRAPH C++ Boost graph algorithms for pgRouting". This is my second time working for pgRouting. I am glad to help contribute to the open source projects.

**Comment by nike0good** [comment]
https://github.com/pgRouting/GSoC-pgRouting/pull/164

**Comment by cvvergara** [comment]
The check boxes here are for my use. its a guide for me/you to see what I've checked

**Comment by cvvergara** [comment]
Links to tasks are missing.
