### ISSUE TITLE
Intent of application by Anand Kumar 

### ISSUE THREAD

**Issue by AnandIISc** [pgRouting/GSoC-pgRouting#163]
- [x] Intent of application 
- [ ] Experience with GitHub & Git
- [ ] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

**Comment by cvvergara** [comment]
Please write a paragraph about your self here in a comment

**Comment by AnandIISc** [comment]
Hi, I am Anand Kumar. I am a Master's student at the Indian Institute of Science Bangalore, have done Bachelors's in Information. 
Technology. I am having a good knowledge of C++, Data Structures and Algorithms, DBMS. I love contributing to open source, as it is always a great learning experience. Besides contributing to open source, I found projects in pgRouting to be very exciting and match my skillsets. I would like to contribute to pgRouting.

**Comment by cvvergara** [comment]
Did not apply to pgRouting
