### ISSUE TITLE
Intent of Application of Rishi Sethia

### ISSUE THREAD

**Issue by rishisethia258** [pgRouting/GSoC-pgRouting#198]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by rishisethia258** [comment]
### Task 1
Hello, My name is Rishi Sethia. I am an undergraduate student currently in my 3rd year at the Indian Institute of Technology, Roorkee, India. My interest mainly lies in Discrete Mathematics and Data Structures. I have decent knowledge working with C++, Data structures and Algorithms, Git, and Github. I am also active as a Competitive Programmer on various online judges. 
I am looking forward to contributing to pgRouting and participating in GSoC 2022.

**Comment by rishisethia258** [comment]
### Task 2 - Experience with GitHub & Git
- Issue  : rishisethia258#1
- Pull Request : pgrouting#199

**Comment by rishisethia258** [comment]
### Task 3: Build locally pgRouting
- Issue : rishisethia258#2

**Comment by rishisethia258** [comment]
### Task 4: Get familiar with C++
- Issue : rishisethia258#3

**Comment by rishisethia258** [comment]
### Task 5: Get familiar with pgRouting
- Issue : rishisethia258#4

**Comment by rishisethia258** [comment]
Please review @cvvergara @krashish8 @veenits123

**Comment by krashish8** [comment]
Provisionally reviewed, so that you can start getting familiar with pgRouting or work on your [GSoC idea](https://github.com/pgRouting/pgrouting/wiki/GSoC-Ideas:-2022).
As always, we would make a final review when we evaluate the proposals.

**Comment by krashish8** [comment]
Did not apply
