### ISSUE TITLE
Creating your wiki page for the program.

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/GSoC-pgRouting#2]
1) I just sent an invitation for you to be able to access the pgRouting wiki page, please accept the invitation.
2) Edit https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code and add to the top of the list:
```
* Name ([[GSoC 2019 project title | GSoC-2019-project-title]]) university name
```
of course with your own information.

Then you will be editing `GSoC-2019-project-title`, the link will automatically will be created when you finish the edition.

3) edit `GSoC-2019-project-title`
Some preferences apply: (not compulsory)

-    Most recent comes first, that way mentors don't have to scroll down to find the most recent thing.
-    Have sub indexes on the sections
    Some rules apply: (compulsory)
-    Have a general index.

Look around on other's students wiki, and choose the one of your preference as guidance

4) content of wiki page

-    Please guide yourself with other's students wiki
-    Break it up in evaluation periods and each one to have the corresponding weeks (add dates to the weeks)
    Week 1: <date from> to <date to>
-    If your country or religion have a holiday please leave a note on the corresponding week of those dates.

5) Add the following sections also
  - Community Bonding Period
    -  Add a short explanation of the things you are doing during this period
  - Pre-Bonding Period
    - and on the Pre-Bonding Period add links to the things (issues & PR) that you made while making the proposal
6) Please have your wiki prepared for next week

**Comment by vicennial** [comment]
Done.   
Link to the wiki -> [https://github.com/pgRouting/pgrouting/wiki/GSoC-2019-Edward-Moore's-Algorithm,-Breadth-First-Search-and-Binary-Breadth-First-Search](https://github.com/pgRouting/pgrouting/wiki/GSoC-2019-Edward-Moore's-Algorithm,-Breadth-First-Search-and-Binary-Breadth-First-Search)

**Comment by nike0good** [comment]
Done.
Link to the wiki -> https://github.com/pgRouting/pgrouting/wiki/GSoC-2019-GRAPH-C---Boost-graph-algorithms-for-pgRouting
