### ISSUE TITLE
Intent of Application - Sanskar Bhushan

### ISSUE THREAD

**Issue by sbdtu5498** [pgRouting/GSoC-pgRouting#204]
- [x] Intent of application
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

**Comment by sbdtu5498** [comment]
Hello pgRouting community, I am Sanskar Bhushan, a junior year student from Delhi Technological University currently pursuing B.Tech in Engineering Physics. I have previous experience in implementing data structures and algorithms from scratch in various programming languages such as C and C++. Being passionate about the open source technologies, I have always wanted to contribute in an open source project and pgRouting is an interesting project that combines my understanding of graph algorithms with the real world problem that we tackle in our everyday life. Thus, I want to contribute in the project so that I can learn more about the pgRouting and at the same time, give back to the community.

**Comment by sbdtu5498** [comment]
### Task 3 - Build Locally pgRouting

**Comment by sbdtu5498** [comment]
### Get Familiar with C++

**Comment by sbdtu5498** [comment]
@cvvergara please review.

**Comment by krashish8** [comment]
Provisionally reviewed. You can start getting more familiar with pgRouting and simultaneously work on your [GSoC idea](https://github.com/pgRouting/pgrouting/wiki/GSoC-Ideas:-2022).
We would do a final review when we evaluate the proposals.

**Comment by krashish8** [comment]
@sbdtu5498 Please share the proposal link here and/or submit it in the GSoC Dashboard if you haven't.
You can always re-submit the pdf in the dashboard, so it is good to submit early to avoid last-minute hurries.

**Comment by sbdtu5498** [comment]
Yes I have already submitted it few hours ago and shared it on the Gitter as well. Just saw your message, sorry for the late reply. 
[Link to the final draft of the proposal submitted for GSoC 2022](https://docs.google.com/document/d/1l8kEp_DSUA5g0pn-H14zxf8psc_wyo8H1VmgtkoPUfk/edit#).
