### ISSUE TITLE
Copy by hand mail from OSGeo-GSoC administrators

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/GSoC-pgRouting#3]
From OSGeo-GSoC administrators
https://lists.osgeo.org/pipermail/discuss/2019-May/038354.html

**Comment by cvvergara** [comment]
Other mail from the administrators to be copied
https://lists.osgeo.org/pipermail/discuss/2019-May/038353.html

# IMPORTANT
not only copy the mail, but also do what they ask

**Comment by vicennial** [comment]
GSoC selections announcement email ([https://lists.osgeo.org/pipermail/discuss/2019-May/038353.html](https://lists.osgeo.org/pipermail/discuss/2019-May/038353.html)) :  
![p1](https://user-images.githubusercontent.com/21010250/57363680-3b4ab000-719f-11e9-97e0-29b902d32438.png)

Community Bonding Instructions Email ([https://lists.osgeo.org/pipermail/discuss/2019-May/038354.html](https://lists.osgeo.org/pipermail/discuss/2019-May/038354.html)) : 

![p2](https://user-images.githubusercontent.com/21010250/57363806-764ce380-719f-11e9-9220-ed6774d25b2e.png)

![p3](https://user-images.githubusercontent.com/21010250/57363809-7816a700-719f-11e9-816e-3cfc6d36d04e.png)

![p4](https://user-images.githubusercontent.com/21010250/57363812-7947d400-719f-11e9-90fd-4193cbc98b8f.png)

**Comment by nike0good** [comment]
Community Bonding Instructions Email (https://lists.osgeo.org/pipermail/discuss/2019-May/038354.html) :
![pic1](https://img-blog.csdnimg.cn/20190513184538170.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L25pa2UwZ29vZA==,size_16,color_FFFFFF,t_70)
![pic2](https://img-blog.csdnimg.cn/20190513184705811.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L25pa2UwZ29vZA==,size_16,color_FFFFFF,t_70)
![pic3](https://img-blog.csdnimg.cn/20190513184603859.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L25pa2UwZ29vZA==,size_16,color_FFFFFF,t_70)
