### ISSUE TITLE
withPoints  X  

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/GSoC-pgRouting#300]
```
pgr_withPointsDD(Edges SQL, Points SQL, root vid, distance, [options A])
options A: [directed, driving_side, details]
```

become
```
pgr_withPointsDD([Edges SQL, Points SQL, root vid, distance, driving side, [options A])
options A: [directed,  details]
```

"Both" is only valid on undirected graphs

**Comment by krashish8** [comment]
What if the graph is undirected and the end pgRouting user gave 'b' driving_side? Shall we raise an SQL error in that case?

Also, what will shall be the default value of driving side - same as before ('b') or are we changing it to 'r' for 3.6 onwards?

**Comment by squarege** [comment]
## Confuse:
In the change @cvvergara  do [here](https://github.com/cvvergara/pgrouting/blob/22075936d1ad8b5a907f3f2a747f427e525864d5/src/driving_distance/withPointsDD.c#L64-L81), in fact, `[r,l,b]` all treated as `b` on undirected graphs, and `b` is still valid on directed graphs. It's different from what we [discussed before](https://github.com/pgRouting/GSoC-pgRouting/issues/300#issue-1752938940) in which `"Both" is only valid on undirected graphs`.

Should I throw an error when `b` is given on directed graphs?

**Comment by cvvergara** [comment]
Lets read a little:
https://docs.pgrouting.org/latest/en/withPoints-family.html#driving-side

**Comment by squarege** [comment]
## Summary of the discussion in Gitter
When thinking of vehicles:
- There are countries with left side driving, like India, UK
- There are countries with right side driving, like Mexico, China
- No country has both sides driving
- Directed graph is used to represent streets for vehicles

When thinking of pedestrians:
- They can go in both directions in any case.
- `driving side` is meaningless for pedestrians.
- Undirected graph used to represent sidewalks.

Q: What would be the best default value of "driving side" for vehicles
A: `r` as default for vehicles, reasons:
- Most of app are for vehicles, and can only choose between `r` & `l`.
- Most of countries are right side driving.
- So `r` is more suitable for most cases.
