### ISSUE TITLE
List of possible implementations from boost

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/GSoC-pgRouting#360]
Please use a comment here to indicate you work intention,

For example, suppose that pgr_dijsktra does not exist, and I am planning to work on it, so in a comment in this issue I write:

I am Vicky Vergara
Planning to implement: https://www.boost.org/doc/libs/1_84_0/libs/graph/doc/dijkstra_shortest_paths.html
with a tentative name: `pgr_dijkstra`

**Comment by dikwickley** [comment]
I am Aniket Singh Rawat
Planning to implement: https://www.boost.org/doc/libs/1_82_0/libs/graph/doc/topological_sort.html
with a tentative name: `prg_toposort`
<details>
  <summary>Why?</summary> 
 
Topological sorting has many real world use cases
- Dependency resolution
- Task Scheduling
- Deadlock detection
- and many others
</details>

**Comment by cvvergara** [comment]
@dikwickley We already have topological sort implemented
https://docs.pgrouting.org/latest/en/pgr_topologicalSort.html

**Comment by dikwickley** [comment]
@cvvergara Thanks for pointing that out. I would like to implement another one of Sparse Matrix Ordering Algorithms.


I am Aniket Singh Rawat
Planning to implement: https://www.boost.org/doc/libs/1_82_0/libs/graph/doc/sloan_ordering.htm
with a tentative name: `pgr_sloanOrdering`

**Comment by Aniket-debug** [comment]
I am Aniket Agarwal

Planning to implement: https://www.boost.org/doc/libs/1_84_0/libs/graph/doc/incremental_components.html

with a tentative name: prg_incrementalComponents

**Comment by dhruvmehtaaa** [comment]
I am Dhruv Mehta
Planning to implement: https://www.boost.org/doc/libs/1_84_0/libs/graph/doc/planar_canonical_ordering.html

with a tentative name: `pgr_planarCanonicalOrdering`

**Comment by livingspring** [comment]
Hi, I am Rongwei Ji
Plananing to implement: https://www.boost.org/doc/libs/1_84_0/libs/graph/doc/howard_cycle_ratio.html

with a tentative name :pgr_maxMinCycleRatio

**Comment by bedupako12mas** [comment]
Hi, I am Arun Thakur
Planning to implement: https://www.boost.org/doc/libs/1_84_0/libs/graph/doc/betweenness_centrality.html

with a tentative name: ```pgr_brandesBetweennessCentrality```
