### ISSUE TITLE
Intent of Application - Rongwei Ji

### ISSUE THREAD

**Issue by wayne-xyz** [pgRouting/GSoC-pgRouting#361]
- [x] Intent of application 
- [x] Code of Conduct reproduction
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

# Intent of Application:
- [x] Write a paragraph about yourself in a comment of this issue.
- [x] Handwrite a copy the [code of conduct](https://github.com/pgRouting/pgrouting/blob/main/CODE_OF_CONDUCT.md)
  - [x] Take a picture of copy and upload on a comment of this issue.

**Comment by livingspring** [comment]
# Task1 
## Intent of application
Greetings, everyone! I'm absolutely delighted to be part of this community and to have the opportunity to connect with all of you. My name is Wayne Rongwei, and I'm currently pursuing my Master's degree in CS at SMU Dallas, with a keen interest in GIS development. Proficient in C++, Python, Javascript, and Swift, I bring a robust skill set to the table.

As I gear up for applying to GSoC 2024, I'm particularly excited about the prospect of contributing to pgRouting. I've identified the Boost Graph Library as a fantastic resource for project ideas within the GSoC framework. I'm eager to delve into its offerings and potentially submit an application in the near future.

Throughout this journey, I greatly appreciate any suggestions and exchanges from all of you. Your insights will be invaluable as I navigate through this process.

**Comment by livingspring** [comment]
Handwrite a copy the [code of conduct](https://github.com/pgRouting/pgrouting/blob/main/CODE_OF_CONDUCT.md)
<details>
  <summary>Click to View the pictures</summary>
![S__1974274_0](https://github.com/pgRouting/GSoC-pgRouting/assets/8085091/974c8e81-f651-4e1e-8b4e-c7aec1a49ce5)
![S__1974276_0](https://github.com/pgRouting/GSoC-pgRouting/assets/8085091/7089a74f-4418-41e2-8685-215f3e4852a0)
![S__1974277_0](https://github.com/pgRouting/GSoC-pgRouting/assets/8085091/240774da-7430-449f-a41f-ea2b325b2433)
![S__1974278_0](https://github.com/pgRouting/GSoC-pgRouting/assets/8085091/a375d57d-84f5-4a37-a125-6b38ae542999)
![S__1974280_0](https://github.com/pgRouting/GSoC-pgRouting/assets/8085091/b3a1a5f7-e356-4fd4-80aa-2e6be06a93dc)
![S__1974278_0](https://github.com/pgRouting/GSoC-pgRouting/assets/8085091/b662a843-3a5d-4012-a706-a1e7e2571cff)

</details>

**Comment by livingspring** [comment]
# Task2  
## Experience with GitHub & Git
Link1: https://github.com/livingspring/GSoC-pgRouting/issues/1
Link2: https://github.com/pgRouting/GSoC-pgRouting/pull/362

**Comment by livingspring** [comment]
# Task 3
## Build locally pgRouting
Link: https://github.com/livingspring/GSoC-pgRouting/issues/2#issuecomment-1963030508

**Comment by livingspring** [comment]
# Task 4: 
## Get familiar with C++

https://github.com/livingspring/GSoC-pgRouting/issues/3#issuecomment-2008389167

**Comment by livingspring** [comment]
# Task 5:
## Get familiar with pgRouting 

links  : https://github.com/livingspring/GSoC-pgRouting/issues/4#issue-2196318766

**Comment by livingspring** [comment]
https://docs.google.com/document/d/1OVsBugOUJXG8jWyNCaMTn2j7L5ZsP6rTH2TeodhoQOk/edit?usp=sharing

Thank you for reviewing and feedback, I will reply promptly and make the necessary modifications before submitting
